import type { NodeCatalogItem, WorkflowDefinition, WorkflowNodeType } from "./types";

export const NODE_CATALOG: NodeCatalogItem[] = [
  {
    type: "manualTrigger",
    label: "Start button",
    description: "Run this workflow when you choose",
    category: "Start",
    defaultConfig: {},
    outcome: "Lets a teammate start the workflow on demand.",
  },
  {
    type: "webhookTrigger",
    label: "Incoming request",
    description: "Start when another system sends data",
    category: "Advanced",
    defaultConfig: { slug: "incoming-request", secretRequired: true },
    outcome: "Creates a secure URL that another approved system can call.",
  },
  {
    type: "scheduleTrigger",
    label: "On a schedule",
    description: "Run automatically at a set time",
    category: "Start",
    defaultConfig: { cron: "0 9 * * 1-5", timezone: "America/New_York" },
    outcome: "Starts the workflow automatically on the schedule you choose.",
  },
  {
    type: "gmailTrigger",
    label: "Read Gmail inbox",
    description: "Collect recent messages for a digest",
    category: "Start",
    defaultConfig: {
      executionMode: "demo",
      connectionRef: "",
      search: "is:unread newer_than:1d",
      maxMessages: 5,
    },
    outcome: "Collects recent email subjects, senders, and snippets without exposing mailbox credentials.",
    setup: "connection",
  },
  {
    type: "ai",
    label: "Summarize with Luna",
    description: "Turn the inbox into an executive brief",
    category: "Think",
    defaultConfig: {
      model: "openai/gpt-5.6-luna",
      systemPrompt: "You are an executive communications assistant. Be concise, factual, and action-oriented.",
      prompt: "Summarize these emails for a business leader. Group them into: Decisions needed, Important updates, and Follow-ups. Include the sender and a clear next action.\n\n{{input.messages}}",
      webSearch: false,
      maxSearchResults: 5,
    },
    outcome: "Creates a concise, action-oriented brief using GPT-5.6 Luna through OpenRouter.",
  },
  {
    type: "condition",
    label: "Condition",
    description: "Route based on a value",
    category: "Advanced",
    defaultConfig: { path: "content", operator: "contains", value: "" },
    outcome: "Sends the workflow down a different path when a business rule matches.",
  },
  {
    type: "transform",
    label: "Transform",
    description: "Map data with safe templates",
    category: "Advanced",
    defaultConfig: { template: "{{input}}" },
    outcome: "Reshapes information into the format the next step expects.",
  },
  {
    type: "delay",
    label: "Delay",
    description: "Pause durably, then continue",
    category: "Advanced",
    defaultConfig: { seconds: 60 },
    outcome: "Pauses the workflow for a set amount of time without losing progress.",
  },
  {
    type: "approval",
    label: "Ask for approval",
    description: "Pause until a teammate reviews it",
    category: "Review",
    defaultConfig: { prompt: "Is this inbox brief ready to share?", approver: "Operations lead" },
    outcome: "Keeps a person in control before anything is shared externally.",
  },
  {
    type: "googleDoc",
    label: "Create Google Doc",
    description: "Save the brief as a shareable document",
    category: "Deliver",
    defaultConfig: {
      executionMode: "demo",
      connectionRef: "",
      title: "Inbox brief — {{input.date}}",
      folder: "OpenWorkflow briefs",
    },
    outcome: "Creates a Google Doc and carries its link into the approval and sharing steps.",
    setup: "connection",
  },
  {
    type: "slack",
    label: "Share in Slack",
    description: "Post the approved document link",
    category: "Deliver",
    defaultConfig: {
      executionMode: "demo",
      connectionRef: "",
      channel: "#leadership-updates",
      message: "The approved inbox brief is ready: {{input.documentUrl}}",
    },
    outcome: "Shares only the approved document link in the chosen Slack channel.",
    setup: "connection",
  },
  {
    type: "http",
    label: "HTTP request",
    description: "Call an approved external API",
    category: "Advanced",
    defaultConfig: { method: "GET", url: "https://api.example.com", headers: "{}", body: "" },
    outcome: "Calls an allowlisted HTTPS endpoint for advanced integrations.",
  },
  {
    type: "daytonaSandbox",
    label: "Daytona sandbox",
    description: "Isolate code, shell, and Git work",
    category: "Compute",
    defaultConfig: {
      language: "typescript",
      snapshot: "",
      networkMode: "blocked",
      allowedDomains: "",
      ttlMinutes: 30,
    },
    outcome: "Creates one ephemeral Daytona sandbox shared by the steps placed inside this boundary.",
    runtime: "daytona",
  },
  {
    type: "code",
    label: "Run code",
    description: "Execute code inside a Daytona sandbox",
    category: "Compute",
    defaultConfig: {
      code: "const input = JSON.parse(process.env.OPENWORKFLOW_INPUT ?? \"null\");\nconsole.log(JSON.stringify({ received: input }));",
      timeoutSeconds: 60,
    },
    outcome: "Runs JavaScript, TypeScript, or Python without giving code access to the OpenWorkflow host.",
    runtime: "daytona",
  },
  {
    type: "shell",
    label: "Run shell command",
    description: "Use an isolated command line",
    category: "Compute",
    defaultConfig: {
      command: "pwd && ls -la",
      workingDirectory: "workspace",
      timeoutSeconds: 60,
    },
    outcome: "Runs a command inside the boundary's isolated filesystem and captures its output.",
    runtime: "daytona",
  },
  {
    type: "git",
    label: "Clone Git repository",
    description: "Bring a repository into the sandbox",
    category: "Compute",
    defaultConfig: {
      repositoryUrl: "https://github.com/example/repository.git",
      directory: "workspace/repository",
      branch: "",
      depth: 1,
    },
    outcome: "Clones a public HTTPS repository into the boundary's shared filesystem.",
    runtime: "daytona",
  },
  {
    type: "output",
    label: "Finish workflow",
    description: "Show the final result to the user",
    category: "Deliver",
    defaultConfig: { outputName: "result" },
    outcome: "Marks the workflow complete and presents its final result.",
  },
];

export const catalogByType = Object.fromEntries(
  NODE_CATALOG.map((item) => [item.type, item]),
) as Record<WorkflowNodeType, NodeCatalogItem>;

export const STARTER_WORKFLOW: WorkflowDefinition = {
  id: "starter-inbox-brief",
  name: "Daily inbox brief",
  description: "Summarize priority Gmail messages, create a Google Doc, get approval, and share it in Slack.",
  enabled: false,
  updatedAt: Date.now(),
  nodes: [
    {
      id: "gmail-1",
      type: "workflow",
      position: { x: 40, y: 210 },
      data: {
        label: "Collect unread email",
        description: "Up to 5 messages from the last day",
        nodeType: "gmailTrigger",
        config: { ...catalogByType.gmailTrigger.defaultConfig },
      },
    },
    {
      id: "ai-1",
      type: "workflow",
      position: { x: 305, y: 210 },
      data: {
        label: "Write executive brief",
        description: "GPT-5.6 Luna through OpenRouter",
        nodeType: "ai",
        config: { ...catalogByType.ai.defaultConfig },
      },
    },
    {
      id: "doc-1",
      type: "workflow",
      position: { x: 570, y: 210 },
      data: {
        label: "Create briefing doc",
        description: "Google Docs (safe demo by default)",
        nodeType: "googleDoc",
        config: { ...catalogByType.googleDoc.defaultConfig },
      },
    },
    {
      id: "approval-1",
      type: "workflow",
      position: { x: 835, y: 210 },
      data: {
        label: "Review before sharing",
        description: "Human approval required",
        nodeType: "approval",
        config: { ...catalogByType.approval.defaultConfig },
      },
    },
    {
      id: "slack-1",
      type: "workflow",
      position: { x: 1100, y: 210 },
      data: {
        label: "Post approved link",
        description: "Slack #leadership-updates",
        nodeType: "slack",
        config: { ...catalogByType.slack.defaultConfig },
      },
    },
  ],
  edges: [
    { id: "e-gmail-ai", source: "gmail-1", target: "ai-1", animated: true },
    { id: "e-ai-doc", source: "ai-1", target: "doc-1", animated: true },
    { id: "e-doc-approval", source: "doc-1", target: "approval-1", animated: true },
    { id: "e-approval-slack", source: "approval-1", target: "slack-1", animated: true },
  ],
};
