import type { NodeCatalogItem, WorkflowDefinition, WorkflowNodeType } from "./types";

export const NODE_CATALOG: NodeCatalogItem[] = [
  {
    type: "manualTrigger",
    label: "Start button",
    description: "Run this workflow when you choose",
    category: "Triggers",
    defaultConfig: {},
    outcome: "Lets a teammate start the workflow on demand.",
  },
  {
    type: "webhookTrigger",
    label: "Incoming request",
    description: "Start when another system sends data",
    category: "Triggers",
    defaultConfig: { slug: "incoming-request", secretRequired: true },
    outcome: "Creates a secure URL that another approved system can call.",
  },
  {
    type: "scheduleTrigger",
    label: "On a schedule",
    description: "Run automatically at a set time",
    category: "Triggers",
    defaultConfig: { cron: "0 9 * * 1-5", timezone: "America/New_York" },
    outcome: "Starts the workflow automatically on the schedule you choose.",
  },
  {
    type: "gmailTrigger",
    label: "Read Gmail inbox",
    description: "Collect recent messages for a digest",
    category: "Triggers",
    defaultConfig: {
      connectionRef: "",
      search: "is:unread newer_than:1d",
      maxMessages: 5,
    },
    outcome: "Collects recent email subjects, senders, and snippets without exposing mailbox credentials.",
    setup: "connection",
  },
  {
    type: "gmailEventTrigger",
    label: "New Gmail message",
    description: "Start when a matching email arrives",
    category: "Triggers",
    defaultConfig: { connectionRef: "", query: "is:unread" },
    outcome: "Polls Gmail for newly arrived messages matching the search query.",
    setup: "connection",
  },
  {
    type: "calendarTrigger",
    label: "Calendar event changed",
    description: "Start when an event is created or updated",
    category: "Triggers",
    defaultConfig: { connectionRef: "", calendarId: "primary" },
    outcome: "Starts with the metadata of a newly created or updated Google Calendar event.",
    setup: "connection",
  },
  {
    type: "driveTrigger",
    label: "Drive file changed",
    description: "Start when a file is created or updated",
    category: "Triggers",
    defaultConfig: { connectionRef: "", folderId: "" },
    outcome: "Watches Google Drive metadata for new or modified files.",
    setup: "connection",
  },
  {
    type: "sheetsTrigger",
    label: "New Sheet row",
    description: "Start when a row is appended",
    category: "Triggers",
    defaultConfig: { connectionRef: "", spreadsheetId: "", range: "Sheet1!A:Z" },
    outcome: "Detects newly appended Google Sheets rows and emits their cell values.",
    setup: "connection",
  },
  {
    type: "ai",
    label: "Agent",
    description: "Research, analyze, or build with optional compute",
    category: "AI",
    defaultConfig: {
      model: "openai/gpt-5.6-luna",
      useCompute: true,
      planFirst: false,
      systemPrompt: "",
      prompt: "Use the workflow input to complete this task. Decide which tools help.\n\n{{input}}",
      maxToolRounds: 12,
      timeoutSeconds: 300,
      webSearch: false,
      maxSearchResults: 5,
    },
    outcome: "Runs an LLM agent. With compute on, it can search, fetch, and use a secure sandbox when the task needs it.",
  },
  {
    type: "webSearch",
    label: "Search the web",
    description: "Look up live information online",
    category: "AI",
    defaultConfig: { query: "", numResults: 5, includeText: true },
    outcome: "Searches the public web through Exa and returns titles, links, and snippets for later steps.",
  },
  {
    type: "condition",
    label: "Condition",
    description: "Route based on a value",
    category: "Logic",
    defaultConfig: { path: "content", operator: "contains", value: "" },
    outcome: "Sends the workflow down a different path when a business rule matches.",
  },
  {
    type: "transform",
    label: "Transform",
    description: "Map data with safe templates",
    category: "Logic",
    defaultConfig: { template: "{{input}}" },
    outcome: "Reshapes information into the format the next step expects.",
  },
  {
    type: "forEach",
    label: "For each item",
    description: "Apply a safe template to every item",
    category: "Logic",
    defaultConfig: { path: "items", template: "{{input}}" },
    outcome: "Processes every item in a list without running arbitrary code.",
  },
  {
    type: "merge",
    label: "Merge branches",
    description: "Combine results from multiple paths",
    category: "Logic",
    defaultConfig: { mode: "append" },
    outcome: "Waits for connected branches and combines the values they produced.",
  },
  {
    type: "delay",
    label: "Delay",
    description: "Pause durably, then continue",
    category: "Logic",
    defaultConfig: { seconds: 60 },
    outcome: "Pauses the workflow for a set amount of time without losing progress.",
  },
  {
    type: "approval",
    label: "Ask for approval",
    description: "Pause until a teammate reviews it",
    category: "Logic",
    defaultConfig: { prompt: "Is this inbox brief ready to share?", approver: "Operations lead" },
    outcome: "Keeps a person in control before anything is shared externally.",
  },
  {
    type: "googleDoc",
    label: "Create Google Doc",
    description: "Save the brief as a shareable document",
    category: "Apps",
    defaultConfig: {
      connectionRef: "",
      title: "Inbox brief — {{input.date}}",
      folder: "OpenWorkflow briefs",
    },
    outcome: "Creates a Google Doc and carries its link into the approval and sharing steps.",
    setup: "connection",
  },
  {
    type: "gmailSend",
    label: "Send Gmail message",
    description: "Email the result to someone",
    category: "Apps",
    defaultConfig: {
      connectionRef: "",
      to: "",
      subject: "Update from OpenWorkflow",
      body: "{{input.content}}",
    },
    outcome: "Sends an email from the connected Gmail account.",
    setup: "connection",
  },
  {
    type: "calendarEvent",
    label: "Create Calendar event",
    description: "Schedule time on a Google Calendar",
    category: "Apps",
    defaultConfig: {
      connectionRef: "",
      calendarId: "primary",
      title: "Follow-up",
      description: "{{input.content}}",
      startIso: "",
      durationMinutes: 30,
    },
    outcome: "Creates a Google Calendar event and carries its link forward. Leave the start time blank to schedule one hour from now.",
    setup: "connection",
  },
  {
    type: "sheetsAppend",
    label: "Append Sheet row",
    description: "Add a row to a Google Sheet",
    category: "Apps",
    defaultConfig: {
      connectionRef: "",
      spreadsheetId: "",
      range: "Sheet1!A:Z",
      values: "",
    },
    outcome: "Appends one row of values to the chosen spreadsheet range. Use commas or a JSON array to separate cells.",
    setup: "connection",
  },
  {
    type: "driveUpload",
    label: "Upload raw file to Drive",
    description: "Save plain-text output as a Drive file",
    category: "Apps",
    defaultConfig: {
      connectionRef: "",
      fileName: "openworkflow-result.txt",
      content: "{{input.content}}",
      folder: "",
    },
    outcome: "Uploads a raw text file to Google Drive. Use Create Google Doc for formatted reports and briefs.",
    setup: "connection",
  },
  {
    type: "slack",
    label: "Share in Slack",
    description: "Post the approved document link",
    category: "Apps",
    defaultConfig: {
      connectionRef: "",
      channel: "#leadership-updates",
      message: "The approved inbox brief is ready: {{input.documentUrl}}",
    },
    outcome: "Shares only the approved document link in the chosen Slack channel.",
    setup: "connection",
  },
  {
    type: "http",
    label: "HTTP request",
    description: "Call an approved external API",
    category: "Logic",
    defaultConfig: { method: "GET", url: "https://api.example.com", headers: "{}", body: "" },
    outcome: "Calls an allowlisted HTTPS endpoint for advanced integrations.",
  },
  {
    type: "daytonaSandbox",
    label: "Sandbox boundary (legacy)",
    description: "Legacy: isolate code, shell, and Git work",
    category: "Compute",
    defaultConfig: {
      language: "typescript",
      snapshot: "",
      networkMode: "blocked",
      allowedDomains: "",
      ttlMinutes: 30,
    },
    outcome: "Creates one ephemeral Daytona sandbox shared by the steps placed inside this boundary. Prefer the Agent step for new workflows.",
    runtime: "daytona",
    hidden: true,
  },
  {
    type: "code",
    label: "Run code (legacy)",
    description: "Legacy: execute code inside a sandbox boundary",
    category: "Compute",
    defaultConfig: {
      code: "const input = JSON.parse(process.env.OPENWORKFLOW_INPUT ?? \"null\");\nconsole.log(JSON.stringify({ received: input }));",
      timeoutSeconds: 60,
    },
    outcome: "Runs JavaScript, TypeScript, or Python without giving code access to the OpenWorkflow host. Prefer the Agent step for new workflows.",
    runtime: "daytona",
    hidden: true,
  },
  {
    type: "shell",
    label: "Run shell (legacy)",
    description: "Legacy: isolated command line",
    category: "Compute",
    defaultConfig: {
      command: "pwd && ls -la",
      workingDirectory: "workspace",
      timeoutSeconds: 60,
    },
    outcome: "Runs a command inside the boundary's isolated filesystem. Prefer the Agent step for new workflows.",
    runtime: "daytona",
    hidden: true,
  },
  {
    type: "git",
    label: "Clone Git (legacy)",
    description: "Legacy: bring a repository into the sandbox",
    category: "Compute",
    defaultConfig: {
      repositoryUrl: "https://github.com/example/repository.git",
      directory: "workspace/repository",
      branch: "",
      depth: 1,
    },
    outcome: "Clones a public HTTPS repository into the boundary's shared filesystem. Prefer the Agent step for new workflows.",
    runtime: "daytona",
    hidden: true,
  },
  {
    type: "output",
    label: "Finish workflow",
    description: "Show the final result to the user",
    category: "Logic",
    defaultConfig: { outputName: "result" },
    outcome: "Marks the workflow complete and presents its final result.",
  },
];

export const catalogByType = Object.fromEntries(
  NODE_CATALOG.map((item) => [item.type, item]),
) as Record<WorkflowNodeType, NodeCatalogItem>;

export const STARTER_WORKFLOW: WorkflowDefinition = {
  id: "starter-inbox-brief",
  name: "Daily inbox brief",
  description: "Summarize priority Gmail messages, create a Google Doc, get approval, and share it in Slack.",
  enabled: false,
  maxConcurrentRuns: 3,
  updatedAt: Date.now(),
  nodes: [
    {
      id: "gmail-1",
      type: "workflow",
      position: { x: 40, y: 210 },
      data: {
        label: "Collect unread email",
        description: "Up to 5 messages from the last day",
        nodeType: "gmailTrigger",
        config: { ...catalogByType.gmailTrigger.defaultConfig },
      },
    },
    {
      id: "ai-1",
      type: "workflow",
      position: { x: 305, y: 210 },
      data: {
        label: "Write executive brief",
        description: "Summarize inbox into decisions and follow-ups",
        nodeType: "ai",
        config: {
          model: "openai/gpt-5.6-luna",
          systemPrompt: "You are an executive communications assistant. Be concise, factual, and action-oriented.",
          prompt:
            "Summarize these emails for a business leader. Group them into: Decisions needed, Important updates, and Follow-ups. Include the sender and a clear next action.\n\n{{input.messages}}",
          timeoutSeconds: 120,
        },
      },
    },
    {
      id: "doc-1",
      type: "workflow",
      position: { x: 570, y: 210 },
      data: {
        label: "Create briefing doc",
        description: "Create the brief in Google Docs",
        nodeType: "googleDoc",
        config: { ...catalogByType.googleDoc.defaultConfig },
      },
    },
    {
      id: "approval-1",
      type: "workflow",
      position: { x: 835, y: 210 },
      data: {
        label: "Review before sharing",
        description: "Human approval required",
        nodeType: "approval",
        config: { ...catalogByType.approval.defaultConfig },
      },
    },
    {
      id: "slack-1",
      type: "workflow",
      position: { x: 1100, y: 210 },
      data: {
        label: "Post approved link",
        description: "Slack #leadership-updates",
        nodeType: "slack",
        config: { ...catalogByType.slack.defaultConfig },
      },
    },
  ],
  edges: [
    { id: "e-gmail-ai", source: "gmail-1", target: "ai-1", animated: true },
    { id: "e-ai-doc", source: "ai-1", target: "doc-1", animated: true },
    { id: "e-doc-approval", source: "doc-1", target: "approval-1", animated: true },
    { id: "e-approval-slack", source: "approval-1", target: "slack-1", animated: true },
  ],
};
